/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnvironmentsRouteImport } from './routes/environments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsCompareRouteImport } from './routes/runs/compare'
import { Route as RunsIdRouteImport } from './routes/runs/$id'
import { Route as EnvironmentsNewRouteImport } from './routes/environments/new'
import { Route as EnvironmentsIdRouteImport } from './routes/environments/$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsRoute = EnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsCompareRoute = RunsCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => RunsRoute,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RunsRoute,
} as any)
const EnvironmentsNewRoute = EnvironmentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EnvironmentsRoute,
} as any)
const EnvironmentsIdRoute = EnvironmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EnvironmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/environments': typeof EnvironmentsRouteWithChildren
  '/login': typeof LoginRoute
  '/runs': typeof RunsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/environments/$id': typeof EnvironmentsIdRoute
  '/environments/new': typeof EnvironmentsNewRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs/compare': typeof RunsCompareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/environments': typeof EnvironmentsRouteWithChildren
  '/login': typeof LoginRoute
  '/runs': typeof RunsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/environments/$id': typeof EnvironmentsIdRoute
  '/environments/new': typeof EnvironmentsNewRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs/compare': typeof RunsCompareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRoute
  '/environments': typeof EnvironmentsRouteWithChildren
  '/login': typeof LoginRoute
  '/runs': typeof RunsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/environments/$id': typeof EnvironmentsIdRoute
  '/environments/new': typeof EnvironmentsNewRoute
  '/runs/$id': typeof RunsIdRoute
  '/runs/compare': typeof RunsCompareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/environments'
    | '/login'
    | '/runs'
    | '/settings'
    | '/environments/$id'
    | '/environments/new'
    | '/runs/$id'
    | '/runs/compare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/dashboard'
    | '/environments'
    | '/login'
    | '/runs'
    | '/settings'
    | '/environments/$id'
    | '/environments/new'
    | '/runs/$id'
    | '/runs/compare'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/dashboard'
    | '/environments'
    | '/login'
    | '/runs'
    | '/settings'
    | '/environments/$id'
    | '/environments/new'
    | '/runs/$id'
    | '/runs/compare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DashboardRoute: typeof DashboardRoute
  EnvironmentsRoute: typeof EnvironmentsRouteWithChildren
  LoginRoute: typeof LoginRoute
  RunsRoute: typeof RunsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments': {
      id: '/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof EnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/compare': {
      id: '/runs/compare'
      path: '/compare'
      fullPath: '/runs/compare'
      preLoaderRoute: typeof RunsCompareRouteImport
      parentRoute: typeof RunsRoute
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof RunsRoute
    }
    '/environments/new': {
      id: '/environments/new'
      path: '/new'
      fullPath: '/environments/new'
      preLoaderRoute: typeof EnvironmentsNewRouteImport
      parentRoute: typeof EnvironmentsRoute
    }
    '/environments/$id': {
      id: '/environments/$id'
      path: '/$id'
      fullPath: '/environments/$id'
      preLoaderRoute: typeof EnvironmentsIdRouteImport
      parentRoute: typeof EnvironmentsRoute
    }
  }
}

interface EnvironmentsRouteChildren {
  EnvironmentsIdRoute: typeof EnvironmentsIdRoute
  EnvironmentsNewRoute: typeof EnvironmentsNewRoute
}

const EnvironmentsRouteChildren: EnvironmentsRouteChildren = {
  EnvironmentsIdRoute: EnvironmentsIdRoute,
  EnvironmentsNewRoute: EnvironmentsNewRoute,
}

const EnvironmentsRouteWithChildren = EnvironmentsRoute._addFileChildren(
  EnvironmentsRouteChildren,
)

interface RunsRouteChildren {
  RunsIdRoute: typeof RunsIdRoute
  RunsCompareRoute: typeof RunsCompareRoute
}

const RunsRouteChildren: RunsRouteChildren = {
  RunsIdRoute: RunsIdRoute,
  RunsCompareRoute: RunsCompareRoute,
}

const RunsRouteWithChildren = RunsRoute._addFileChildren(RunsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DashboardRoute: DashboardRoute,
  EnvironmentsRoute: EnvironmentsRouteWithChildren,
  LoginRoute: LoginRoute,
  RunsRoute: RunsRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
